### ISSUE TITLE
Dumbass example

### ISSUE THREAD

**Issue by KDot227** [qPhantasm/HEHEHE-LOGGING-DUMBASSES#1]
I'm braindead!
Thanks for reading this

**Comment by qPhantasm** [comment]
> https://sped.lol/home
> 
> bro thought nobody would notice

nah dude, it's no secret that I log by myself

**Comment by qPhantasm** [comment]
> https://sped.lol/home
> 
> bro thought nobody would notice

maybe add a vpn detector to your website :D

**Comment by KDot227** [comment]
Top 10 craziest skid moments

**Comment by qPhantasm** [comment]
> Top 10 craziest skid moments

Brother you are the king of the skids himself

**Comment by KDot227** [comment]
> > Top 10 craziest skid moments
> 
> Brother you are the king of the skids himself

hows that 💀

**Comment by KDot227** [comment]
Your grabber is hazard grabber 😭

**Comment by KDot227** [comment]
bro this u 😭 
![image](https://user-images.githubusercontent.com/110929758/205327969-ef32e763-ffb2-4ea9-9846-6d852f78d850.png)

**Comment by KDot227** [comment]
![image](https://user-images.githubusercontent.com/110929758/205329511-05c4be55-9c27-4c5a-97ee-8ffa2fb7c9d4.png)
NO WAY YOU TOOK CREDIT FOR HAZARD GRABBER TOO 💀 💀 💀

**Comment by qPhantasm** [comment]
You fucking dumbass read the readme, i  the first 5 lines I give in the fucking biggest font in caps credits to rdimo so shut the fuck up

**Comment by qPhantasm** [comment]
because his github doesn't exist anymire and it's only fucking me using it so why not dude

**Comment by KDot227** [comment]
> because his github doesn't exist anymire and it's only fucking me using it so why not dude

1.) just cause it no longer exists aint mean u can steal credit.

2.) u post it on GitHub so u can't say u the only one who uses it
